### ISSUE TITLE
[警告]程序错误，无法正常运行！

### ISSUE THREAD

**Issue by msojocs** [msojocs/bilibili-linux#1]
新版似乎做了一些限制，有待处理。

**Comment by Apple-QAQ** [comment]
> 新版似乎做了一些限制，有待处理。

睿站真的太强辣！

**Comment by Apple-QAQ** [comment]
![image](https://user-images.githubusercontent.com/88485487/168412568-94a57f1b-989a-4f41-94b0-75e2a69b8525.png)
有没有可能是这个，在app.asar里面找到的

**Comment by msojocs** [comment]
这是我改的 >_<

**Comment by msojocs** [comment]
定位了
![image](https://user-images.githubusercontent.com/20937135/168413308-f3d9f5bd-f688-4ee8-aea3-df97e2e6ab2f.png)

**Comment by Apple-QAQ** [comment]
> 定位了 ![image](https://user-images.githubusercontent.com/20937135/168413308-f3d9f5bd-f688-4ee8-aea3-df97e2e6ab2f.png)

睿站太狗了

**Comment by Apple-QAQ** [comment]
> 定位了 ![image](https://user-images.githubusercontent.com/20937135/168413308-f3d9f5bd-f688-4ee8-aea3-df97e2e6ab2f.png)

hmmmmm……弄完了建议速速接手aur里的bilibili-bin

**Comment by whtrys** [comment]
也就是说，现在已经解决了这个问题吗？请问直接按照readme构建可以用了吗？

**Comment by Apple-QAQ** [comment]
> 也就是说，现在已经解决了这个问题吗？请问直接按照readme构建可以用了吗？

现在**并没有**解决

**Comment by msojocs** [comment]
行了

**Comment by Apple-QAQ** [comment]
> 行了

快快接手aur上的bilibili-bin！

**Comment by msojocs** [comment]
> > 行了
> 
> 快快接手aur上的bilibili-bin！

弄完了
