### ISSUE TITLE
《这就是中国》显示受限，无法播放，但在浏览器中正常；V1.2的时候版本检测无效，一直提示为最新版本。

### ISSUE THREAD

**Issue by lameisoft** [msojocs/bilibili-linux#101]
![111](https://github.com/msojocs/bilibili-linux/assets/11867757/e5a718fe-076c-4354-afe7-c6a21d0a3ab9)

**Comment by msojocs** [comment]
![image](https://github.com/msojocs/bilibili-linux/assets/20937135/ad20a161-5c61-4bdf-8619-a99101be6e29)
没有复现

**Comment by lameisoft** [comment]
我找到问题了，是因为我设置了系统代理，取消后就好了。感谢您。
