### ISSUE TITLE
评论排序出错

### ISSUE THREAD

**Issue by FadeJay** [msojocs/bilibili-linux#102]
打开一个视频的评论，点击按照最新排序，点开其中一条评论的楼中楼，然后点击返回后会自动变成按照最热排序

**Comment by msojocs** [comment]
官方Windows版本表现是否符合你的预期？

**Comment by FadeJay** [comment]
> 官方Windows版本表现是否符合你的预期？

试了下官方windows版本点击楼中楼返回也是会变成最热排序

**Comment by msojocs** [comment]
那就等官方修。
