### ISSUE TITLE
能否提供按钮字体全局增大的相关选项？

### ISSUE THREAD

**Issue by mirror1776** [msojocs/bilibili-linux#103]
尊敬的开发者：
       界面的相关按钮字体略小，虽然是El**工具开发的软件，用Ctrl+加号并不能放大缩小，请开发者考虑增加个全局放大缩小的按钮或字号的按钮。    

                                                                                                拜谢之
                                                                                                 感激不尽

**Comment by cxw620** [comment]
这个需求得和哔哩哔哩客服提()

**Comment by mirror1776** [comment]
感谢作者的及时回复
