### ISSUE TITLE
希望可以添加对龙芯架构CPU的支持！

### ISSUE THREAD

**Issue by ToKingl** [msojocs/bilibili-linux#108]
如题，希望可以添加对龙芯架构CPU的支持

**Comment by msojocs** [comment]
我没设备，到时候请你反馈能不能用。

**Comment by ToKingl** [comment]
> 我没设备，到时候请你反馈能不能用。 我只能模拟器。

恩恩，龙芯3a6000分为新世界和旧世界https://areweloongyet.com/docs/old-and-new-worlds，所以可能需要打成两个包，旧世界abi1/新世界abi2

**Comment by msojocs** [comment]
https://github.com/msojocs/bilibili-linux/releases/download/continuous/bilibilielectron-v22.3.27-linux-loong64-202405081621.zip

**Comment by ToKingl** [comment]
方便打包一个在loongnix上的deb包吗？

**Comment by msojocs** [comment]
你先看能不能用吧

**Comment by msojocs** [comment]
新世界的现成electron暂时没找到

**Comment by ToKingl** [comment]
我晚上试一下吧，不过旧世界的架构名好像是loongarch64，不是loong64

**Comment by msojocs** [comment]
不清楚，我在这里下的：http://ftp.loongnix.cn/electron/LoongArch/

**Comment by msojocs** [comment]
![image](https://github.com/msojocs/bilibili-linux/assets/20937135/9739af8e-b97a-4701-8726-fe7bff519748)

模拟器太卡了。。。

评论的那个包，我在模拟器（Arch Linux，新世界）启动不了，而且file命令的结果有 GNU/Linux 4.15.0，应该就是旧世界；

我在模拟器的环境里面安装了一个electron包，能启动。

**Comment by msojocs** [comment]
![image](https://github.com/msojocs/bilibili-linux/assets/20937135/1ff5a8ce-87c5-4a4d-bcc9-36e632088855)

理论上打个包就能用。

**Comment by ToKingl** [comment]
我晚上试一下吧，方便在loongnix上打一个deb包吗？新世界上可以通过libLOL的方式来运行旧世界上的软件

**Comment by ToKingl** [comment]
这个应该怎么运行啊，方便大概说一下吗？O(∩_∩)O

**Comment by msojocs** [comment]
解压，给electron可执行权限，然后双击启动，应该就行。

**Comment by ToKingl** [comment]
我还以为要npm run build，原来只需要加个可执行权限就行……，感谢感谢

**Comment by ToKingl** [comment]
刚刚试了一下，这个完全可以使用

**Comment by ToKingl** [comment]
就是打deb包的时候，方便把这个旧世界版的命名为loongarch64吗？所有的旧世界发行版的架构名都统一用的是loongarch64，新世界的话是因为debian系当时嫌名字长所以换成了loong64，rpm系和aosc os的架构名则是用的loongarch64全称，所以用loong64的话会造成部分使用者误认为是新世界版的软件

**Comment by msojocs** [comment]
ok

**Comment by msojocs** [comment]
找了个方法，不用龙芯的仓库（太难崩了，用都用不了）。

命名就按你说的：loongarch64是旧世界，loong64是新世界。

看能不能帮我试一下deb包？

https://github.com/msojocs/bilibili-linux/releases/tag/continuous

**Comment by ToKingl** [comment]
> 找了个方法，不用龙芯的仓库（太难崩了，用都用不了）。
> 
> 命名就按你说的：loongarch64是旧世界，loong64是新世界。
> 
> 看能不能帮我试一下deb包？
> 
> https://github.com/msojocs/bilibili-linux/releases/tag/continuous

不过rpm全系不是通过loong64和loongarch64区分的，他和aosc os一样，在新世界上也延续使用了loongarch64作为架构名，而是通过 abi1/abi2 进行区分的，abi1是旧世界，abi2是新世界，旧世界可以修改为bilibili-loongarch64-abi1-版本号.rpm，新世界则为bilibili-loongarch-abi2-版本号.rpm。

已经在旧世界中进行了测试，可以正常使用，那这个我就关闭了，感谢开发者的适配，辛苦了

**Comment by msojocs** [comment]
ok, rpm这个我晚上看能不能整一下。
