### ISSUE TITLE
svg图标更新

### ISSUE THREAD

**Issue by Peternal** [msojocs/bilibili-linux#109]
之前我绘制的svg图标还有些瑕疵，这次根据官方最新图标重绘了下， 跟官方图标保持一致
![bilibili](https://github.com/msojocs/bilibili-linux/assets/33723146/0f96ea0a-c4f3-481b-9ff5-dd3b2add7a26)
希望能更新替换一下原来的圆形svg图标。

**Comment by msojocs** [comment]
已更新，谢谢。
