### ISSUE TITLE
如何关闭直播页面

### ISSUE THREAD

**Issue by 45degree** [msojocs/bilibili-linux#11]
![image](https://user-images.githubusercontent.com/43808585/169995115-6bbb2629-42a3-4461-b855-626d51783922.png)

如图， 进入直播间之后没有发现直播退出按钮， 点击`回到主界面`  以及`<`   `>`也无法关闭直播窗口。
软件版本为: v1.1.2-2 appimage

**Comment by msojocs** [comment]
https://github.com/msojocs/bilibili-linux/commit/03b7d1e6f760612161f261da109739025b8131a9

已做修正，但未发布版本
