### ISSUE TITLE
关于libuv访问错误

### ISSUE THREAD

**Issue by Tridays** [msojocs/bilibili-linux#117]
非常感谢大大提供的哔哩哔哩Linux包。
我发现一个问题，就是在没有权限访问/proc/net/dev的情况下，nodejs通过代码os.networkInterfaces()获取设备网络信息是报错的：

SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_interface_addresses returned Unknown system error 13 (Unknown system error 13)
    at Object.networkInterfaces (node:os:277:16)
![Screenshot_2024-05-22-13-38-11-981_com termux](https://github.com/msojocs/bilibili-linux/assets/127336245/0b9f3f01-4448-4f36-ab42-bb497c9b39af)

错误重现：
1.安卓手机安装Termux（https://github.com/termux/termux-app）
2.使用proot或proot-distro安装任意Linux系统，如ubuntu（类似于在容器内使用ubuntu）
3.在ubuntu里面安装好桌面环境+bilibili-arm.deb
4.执行/opt/apps/io.github.msojocs.bilibili/files/bin/bin/bilibili

提示：在Android版本≥10的手机上，已经限制应用制访问/proc/net/dev。

在有root的情况下可以正常获取网络信息，并且经过测试可以打开哔哩哔哩
![Screenshot_2024-05-22-13-49-47-965_com termux](https://github.com/msojocs/bilibili-linux/assets/127336245/a492b38a-c503-471a-b6b6-db7ebd24bf0b)

请问是否能修复大部分手机没有root的情况下，能够使用哔哩哔哩，或者说哔哩哔哩他一定要获取设备的网络信息吗？

**Comment by msojocs** [comment]
软件包是给桌面端用的，移动端不管（
