### ISSUE TITLE
kde 窗口

### ISSUE THREAD

**Issue by wyf9661** [msojocs/bilibili-linux#119]
您好，非常感谢您维护bilibili-linux这个repo, 升级到1.13.5版本后，在kde桌面使用新版appimage时，打开窗口会额外多一个kde默认窗口，如果隐藏，这个窗口就不能拖动了，现象如下：

1.13.4版本是正常的, 在aur仓库的[bilibili-bin](https://aur.archlinux.org/packages/bilibili-bin)也有人反映有这个问题

EDIT:
描述有点问题，不是多了kde的默认窗口，是多了默认标题栏

**Comment by msojocs** [comment]
截张图看看

**Comment by wyf9661** [comment]
这是之前的版本
![screenshot-20240529-103234](https://github.com/msojocs/bilibili-linux/assets/122584107/37dc7818-5111-4485-a285-34f5f1ee5de5)

**Comment by wyf9661** [comment]
这是新版本
![image](https://github.com/msojocs/bilibili-linux/assets/122584107/87a32b05-0a35-4c7f-80ac-370a86efb8d1)

**Comment by msojocs** [comment]
这是标题栏，不是窗口啊。

有空修修。

**Comment by wyf9661** [comment]
是的，问题描述的有点问题，好的，非常感谢:)

**Comment by xmb505** [comment]
我今天apt upgrade之后也有这个问题，特地来看看，先降版本用会吧
