### ISSUE TITLE
最小化到托盘后无法恢复

### ISSUE THREAD

**Issue by nesteiner** [msojocs/bilibili-linux#123]
你好，我这边用的 kde wayland，x11上还没试过
每次最小化到窗口后，无法将其恢复，都要重新启动一次，
这是我的系统
Linux archlinux 6.9.2-arch1-1 #1 SMP PREEMPT_DYNAMIC Sun, 26 May 2024 01:30:29 +0000 x86_64 GNU/Linux

**Comment by mlfhls** [comment]
尝试安装gtk2/3/4。看看是否有效
