### ISSUE TITLE
mac os能打包一个吗？或者教我怎么打包下

### ISSUE THREAD

**Issue by bluesmi** [msojocs/bilibili-linux#124]

**Comment by msojocs** [comment]
我没mac，不知道。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月23日(周二) 晚上9:51
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [msojocs/bilibili-linux] mac os能打包一个吗？或者教我怎么打包下 (Issue #124)

**Comment by bluesmi** [comment]
好的，谢谢
