### ISSUE TITLE
安装失败怎么办？

### ISSUE THREAD

**Issue by mymcbbs** [msojocs/bilibili-linux#127]
主要就是安装错误 exit 127
![Uploading Screenshot_2024-09-15-08-44-56-91_2279741c0dede0d4ce8cbad47dbe178c.jpg…]()

**Comment by mymcbbs** [comment]
![Screenshot_2024-09-15-08-46-34-13_2279741c0dede0d4ce8cbad47dbe178c](https://github.com/user-attachments/assets/c1bb3d76-9b7b-4e44-89e5-bdc389258b40)

**Comment by msojocs** [comment]
release里面的包你用不了？

**Comment by Spade6-v** [comment]
我也出现了 exit127
