### ISSUE TITLE
点击用户的id或头像无法进入其主页。

### ISSUE THREAD

**Issue by LckHot** [msojocs/bilibili-linux#128]
一个很频繁发生的bug，触发该bug时，在大多数界面都无法通过点击其他用户的id或头像进入其主页。从关注的人页面点击已关注的用户看起来不受该bug影响。

**Comment by msojocs** [comment]
![image](https://github.com/user-attachments/assets/ed253461-1033-4c04-bf6a-7fcfdfb428a5)

我从评论区点是正常的，你是在哪个页面怎么操作的。

**Comment by msojocs** [comment]
我使用AppImage版本，无法复现以上操作。

请尝试使用AppImage版本

**Comment by msojocs** [comment]
那就是aur的问题，这我没参与维护。
