### ISSUE TITLE
是否可以添加外置播放器支持,以获得svp插帧

### ISSUE THREAD

**Issue by Shapaper233** [msojocs/bilibili-linux#129]
如题
svp插帧很早应该就有linux版了,window的bilibili没有人做二次开发,看此项目有添加漫游等高级功能,不知有没有希望能实现

**Comment by msojocs** [comment]
不会支持。

**Comment by Shapaper233** [comment]
有可能支持外置播放器吗?
比如mpv vlc
不过electron很难实现吧😂
