### ISSUE TITLE
重启后默认静音

### ISSUE THREAD

**Issue by Peternal** [msojocs/bilibili-linux#13]
![image](https://user-images.githubusercontent.com/33723146/170369630-b119ec22-30d4-45d9-927a-a02f6e1e5101.png)
好像每次重启后打开一个视频，声音是默认静音的

**Comment by msojocs** [comment]
Feature Request ?
Bug ?

**Comment by Peternal** [comment]
感觉应该算个Bug吧，就是每次重新开启软件后打开视频都要重新开启一遍声音，而不是记忆上一次的声音设置

**Comment by msojocs** [comment]
若windows存在此问题，应向官方反应；
若只在linux存在此问题，则为移植bug。

**Comment by msojocs** [comment]
此请求意义不大，且实现涉及存储，暂不考虑。
