### ISSUE TITLE
手动构建失败

### ISSUE THREAD

**Issue by huboshi** [msojocs/bilibili-linux#130]
在安装是报“_/home/abc/bilibili-linux/tools/update-bilibili: 行 31: exiftool: 未找到命令 失败  command: BILIBILI_VERSION=$(exiftool -S -ProductVersionNumber "$root_dir/cache/bili_win-install.exe")at /home/abc/bilibili-linux/tools/update-bilibili:31at_ ”
但实际上我安装了exiftool,请问如何解决

**Comment by msojocs** [comment]
从你提供的错误信息看来，虽然你已经安装了 `exiftool`，但这个工具可能没有被添加到环境变量中，导致脚本在运行时找不到这个命令。

请尝试以下步骤来解决这个问题：

1. 确认 `exiftool` 是否安装成功：
   打开一个新的终端（terminal），输入 `exiftool` 然后按回车。如果安装成功，你应该能看到 `exiftool` 的使用说明或版本信息。如果显示“未找到命令”或类似信息，说明 `exiftool` 没有安装成功。

2. 确认 `exiftool` 的安装位置：
   如果确定 `exiftool` 已安装，可以使用 `which exiftool` 或 `whereis exiftool` 命令找出它的安装位置。

3. 将 `exiftool` 所在目录添加到环境变量：
   如果找到了 `exiftool` 的安装位置，你需要将其添加到环境变量 `PATH` 中，这样系统在任何位置都可以找到这个命令。你可以使用以下命令临时添加到当前会话的环境变量中（以 `/usr/local/bin/exiftool` 为例）：

   ```bash
   export PATH=$PATH:/usr/local/bin
   ```

   如果想要永久添加到环境变量，可以将类似上面的命令添加到你的 `~/.bashrc` 或者 `~/.profile` （取决于你使用的 shell）文件中，然后运行 `source ~/.bashrc` 或 `source ~/.profile` 来重新加载配置。

4. 重新运行你的安装脚本：
   在确保 `exiftool` 可以被找到之后，再次尝试运行你的安装脚本。

如果按照以上步骤依然无法解决问题，建议提供更多关于你的操作系统和如何安装 `exiftool` 的详细信息，以便获取更具体的帮助。

**Comment by huboshi** [comment]
我的系统是Arch Linux,输入exiftool可以看到看到exiftool的使用说明或版本信息，将exiftool的安装目录添加到了环境变量中，但是还是报同样的错误。

**Comment by msojocs** [comment]
在终端执行 exiftool 文件 看是否能正常返回文件的元信息，如果不能，可能是exiftool的问题，可以考虑重装一下。

如果 exiftool 文件 能正常执行，那么可能是脚本文件的问题。 

可以尝试在脚本的开始部分添加一行，指定脚本运行时使用的 shell，如：

```bash
#!/bin/bash
```

或

```bash
#!/bin/sh
```

这样做的目的是确保脚本运行时使用的是你预期的 shell。因为不同的 shell 可能会有不同的环境变量设置，可能会影响到 exiftool 的运行。

另外，在脚本中使用绝对路径调用 exiftool，而非相对路径或直接调用，也许能解决你的问题。例如，将脚本中的 exiftool 修改为 /usr/local/bin/exiftool（需要替换为你自己的 exiftool 安装路径）。

如果上述都不能解决问题，建议阅读脚本文件，检查是否有其他可能导致错误的地方。如果脚本来源于第三方，你也可以考虑联系脚本的作者或者在相关论坛寻求帮助。
