### ISSUE TITLE
新版本1.1.3运行不了

### ISSUE THREAD

**Issue by CN-Tower** [msojocs/bilibili-linux#14]
好像叔叔的加密方式又升级了~

**Comment by msojocs** [comment]
get

**Comment by msojocs** [comment]
鼠鼠的加密已经解了，
但是，想之前那样解除限制后不能启动。

![image](https://user-images.githubusercontent.com/20937135/170521615-cb634b1b-6cb3-4440-b1c5-91042a20b82f.png)

**Comment by CN-Tower** [comment]
> 鼠鼠的加密已经解了； 但是，像之前那样解除限制后不能启动，原因有待排查。
> 
> 有兴趣的可以一起研究。
> 
> ![image](https://user-images.githubusercontent.com/20937135/170521615-cb634b1b-6cb3-4440-b1c5-91042a20b82f.png)

我一直卡在002，大佬003怎么出现的：
<img width="484" alt="image" src="https://user-images.githubusercontent.com/20727404/170530800-fa92662f-899e-48de-83cd-2ae959c6544c.png">

“鼠鼠的加密已经解了”
---------------------------
是指解开了那个.biliapp文件吗？

**Comment by CN-Tower** [comment]
> 鼠鼠的加密已经解了； 但是，像之前那样解除限制后不能启动，原因有待排查。
> 
> 有兴趣的可以一起研究。
> 
-------------------
一直卡在002，大佬003是怎么出来的？运行`tools/app-decrypt.js`好像也解不开`.appkey`

**Comment by msojocs** [comment]
这个解的是biliapp

原来是16进制字符串

解了之后是混淆的js

https://github.com/msojocs/bilibili-linux/discussions/17

**Comment by msojocs** [comment]
大概可能已经处理好了

**Comment by msojocs** [comment]
已处理
