### ISSUE TITLE
弹幕屏蔽等级

### ISSUE THREAD

**Issue by oblivcheck** [msojocs/bilibili-linux#145]
这个功能在官方的某一版中被移除了，此项目有计划恢复该功能吗？

**Comment by msojocs** [comment]
有空整一下

**Comment by msojocs** [comment]
加完了

**Comment by oblivcheck** [comment]
似乎没有作用
F12中还看到下面的错误:
![image](https://github.com/user-attachments/assets/9fe8126b-ef63-45cf-95ed-ace6f08b4ad9)

**Comment by msojocs** [comment]
这个错误是正常的

**Comment by msojocs** [comment]
先关了，有其它问题开新issue。
