### ISSUE TITLE
[Feature Request] 给弹幕 Ext & 弹幕时间轴加上图标

### ISSUE THREAD

**Issue by alex3236** [msojocs/bilibili-linux#20]
如题。

### 弹幕填充
[![](https://cdn4.iconfinder.com/data/icons/ionicons/512/icon-ios7-cloud-64.png)](https://www.iconfinder.com/icons/211724/cloud_icon)

### 弹幕时间轴
[![](https://cdn3.iconfinder.com/data/icons/fluent-solid-24px-vol-8/24/ic_fluent_timeline_24_filled-64.png)](https://www.iconfinder.com/icons/8674132/ic_fluent_timeline_filled_icon)

**Comment by msojocs** [comment]
已在新版添加
