### ISSUE TITLE
多级弹窗期待合并一个窗体

### ISSUE THREAD

**Issue by GershonWang** [msojocs/bilibili-linux#24]
多级弹窗请求能不能合并成一个窗体？
主要造成的影响是，经常因为某些原因会将哔哩哔哩APP最小化，等再次点击任务栏的时候打开的并不是播放视频界面，而是主窗体，每次得多点几次任务栏才能打开出来播放界面

**Comment by msojocs** [comment]
不可能，请向官方反馈此问题。
