### ISSUE TITLE
希望添加arm64处理器的发行版

### ISSUE THREAD

**Issue by nimade2333** [msojocs/bilibili-linux#25]
如题

**Comment by msojocs** [comment]
加了，但是我没有 arm64 的设备，不保证可用性尝试一下：

https://github.com/msojocs/bilibili-linux/releases/tag/continuous

**Comment by nimade2333** [comment]
> 加了，但是我没有 arm64 的设备，不保证成功，试用：
> 
> https://github.com/msojocs/bilibili-linux/releases/tag/continuous

可以加个deb安装包吗

**Comment by nimade2333** [comment]
> > > 加了，但是我没有arm64的设备，不保证成功，试试：
> > > https://github.com/msojocs/bilibili-linux/releases/tag/continuous
> > 
> > 
> > 可以加个deb安装包吗
> 
> 你先看看appimage能不能用，deb之后再考虑

#
![Screenshot_2022-06-15-09-57-06-497_com realvnc viewer android](https://user-images.githubusercontent.com/78244426/173859359-38ba14aa-0dc0-4d2c-b304-aab6d9a0327e.jpg)

**Comment by nimade2333** [comment]
> 麻烦测试一下 deb 的 arm64，谢谢。 https://github.com/msojocs/bilibili-linux/releases/tag/continuous

好

**Comment by nimade2333** [comment]
> 麻烦测试一下 deb 的 arm64，谢谢。 https://github.com/msojocs/bilibili-linux/releases/tag/continuous

大佬牛逼，可以
![Screenshot_2022-06-17-15-52-39-811_com realvnc viewer android](https://user-images.githubusercontent.com/78244426/174399669-fd94d3f6-2759-4e9e-9cc6-8008380def92.jpg)

**Comment by msojocs** [comment]
我很好奇你这个系统是在云服务器？

**Comment by nimade2333** [comment]
> 我很好奇你这个系统是在云服务器？
> 
> 编辑：
> deb 怎么有个标题栏，怪。

用termux加tmoe弄出来的

**Comment by msojocs** [comment]
ok，关闭issue
