### ISSUE TITLE
[Suggest] A suggestion about the taskbar icon

### ISSUE THREAD

**Issue by Apple-QAQ** [msojocs/bilibili-linux#3]
It is recommended to add open software in the taskbar menu or left-click to open the app and right-click to open the menu
建议在任务栏菜单中添加打开软件或左键打开软件，右键打开菜单
![image](https://user-images.githubusercontent.com/88485487/168427271-3676ade3-65e5-4a0e-94b8-40e9eaefbb0a.png)

**Comment by msojocs** [comment]
建议点击 <kbd>意见反馈</kbd> ，向官方反馈此问题

**Comment by msojocs** [comment]
在检查 #6 是顺便加了一个首页入口

**Comment by msojocs** [comment]
已处理
