### ISSUE TITLE
统信相关平台更新失败

### ISSUE THREAD

**Issue by zkitefly** [msojocs/bilibili-linux#32]
Linux：UOS家庭版 21.3
客户端版本![image](https://user-images.githubusercontent.com/64117916/175814185-462582a0-ce44-4b36-8e5c-1d85a73c4a41.png)
![录屏_bilibili_20220626202325](https://user-images.githubusercontent.com/64117916/175814223-0ac2caeb-408b-46f8-a458-93d6e322352d.gif)

或许是更新渠道还是bilibili的，也许可以将更新渠道变更成可用的？

**Comment by msojocs** [comment]
统信相关平台暂停维护。
