### ISSUE TITLE
Error launching app

### ISSUE THREAD

**Issue by faight4869** [msojocs/bilibili-linux#33]
直接手动构建出现以下问题：

Unable to find Electron app at /home/yi/software/bilibili-linux/app/app.asar

Cannot find module '/home/yi/software/bilibili-linux/app/app.asar'
Require stack:
- /home/yi/software/bilibili-linux/electron/resources/default_app.asar/main.js
-

**Comment by msojocs** [comment]
请详细描述您的操作流程

**Comment by msojocs** [comment]
无后续
