### ISSUE TITLE
VA-API 视频硬件解码支持

### ISSUE THREAD

**Issue by YidaozhanYa** [msojocs/bilibili-linux#34]
Chromium 在 Linux 平台下默认不会硬解视频，在原版 Chromium 中可以通过加入 `--enable-features=VaapiVideoDecoder` 命令行参数打开视频硬解功能，而此客户端加入参数之后，仍然不会硬解视频，所以希望在客户端代码中加入 `app.commandLine.appendSwitch('enable-features', 'VaapiVideoDecoder')` 来允许视频硬解。

**Comment by msojocs** [comment]
试过了，好像没有作用

**Comment by msojocs** [comment]
如果在electron下测试通过并有证明，再考虑添加。
