### ISSUE TITLE
希望支持个性化窗口管理器风格

### ISSUE THREAD

**Issue by cynosure279** [msojocs/bilibili-linux#35]
希望允许使用系统自带窗口管理器（最好能像google chrome那样选择设置窗口管理器风格），这样有利于风格上的一致性
当然这并非bug或性能问题，但是我仍然希望能支持这样的操作

**Comment by msojocs** [comment]
有哪个electron应用是这样的？举个例子

**Comment by msojocs** [comment]
意义不明，暂不能理解。
