### ISSUE TITLE
[Feature Request] 正确的任务图标

### ISSUE THREAD

**Issue by alex3236** [msojocs/bilibili-linux#4]
### 当前图标
![图片](https://user-images.githubusercontent.com/45303195/168431261-217fa9cc-c59c-459b-b34f-b2575587fe97.png)

### 预期图标
与托盘图标相同

**Comment by msojocs** [comment]
这是我看到的
![image](https://user-images.githubusercontent.com/20937135/168431792-ec25a32f-0847-421f-b3af-b845513772e5.png)

**Comment by msojocs** [comment]
建议留下桌面信息，以供参考。

**Comment by alex3236** [comment]
草 忘了系统信息了（
```plain
OS: Manjaro Linux x86_64 
Kernel: 5.15.32-1-MANJARO 
DE: Plasma 5.24.4 
WM: KWin 
CPU: 11th Gen Intel i5-11260H (12) @ 4.400GHz 
GPU: NVIDIA GeForce RTX 3050 Mobile 
Memory: 8270MiB / 15834MiB                            
```

**Comment by alex3236** [comment]
补充下 托盘图标是正常的，任务栏图标不对

**Comment by msojocs** [comment]
你是指这个任务栏？
![image](https://user-images.githubusercontent.com/20937135/168454086-7120033b-15fd-42b6-8856-4b9a695dfa20.png)

**Comment by alex3236** [comment]
> 你是指这个任务栏？ ![image](https://user-images.githubusercontent.com/20937135/168454086-7120033b-15fd-42b6-8856-4b9a695dfa20.png)

是的。你好像是 gnome？我 KDE，图标没出来

**Comment by msojocs** [comment]
你系统有装这个吗？
`libappindicator-gtk3`

**Comment by alex3236** [comment]
> 你系统有装这个吗？ `libappindicator-gtk3`

有的

![图片](https://user-images.githubusercontent.com/45303195/169326271-3fe8228f-c60f-490a-aef8-38754c0cf2f7.png)

**Comment by msojocs** [comment]
https://github.com/electron/electron/issues/32577
似乎要安装的那种模式才能显示；
我这边由于设备限制，不能进一步测试；
你可以尝试修改 `desktop` 复制到 `/usr/share/applications` 下面看能不能行；
如果可以的话，后面再写个简单安装卸载脚本辅助一下。

**Comment by msojocs** [comment]
记录：发现deepin也存在该问题

**Comment by Peternal** [comment]
ubuntu 22.04 也存在该问题
![image](https://user-images.githubusercontent.com/33723146/170368957-419d41b0-7819-4729-a0fa-c51424d1e571.png)

**Comment by msojocs** [comment]
在manjaro下：
1. 卸载AUR包
2. 打开程序
3. 图标为齿轮

可以确定是“图标要装在系统里面”

**Comment by msojocs** [comment]
已发布新的版本

**Comment by Peternal** [comment]
新版本图标已可以正常显示，但是会出现色彩断层
![截图 2022-05-30 22-01-51](https://user-images.githubusercontent.com/33723146/171078635-a116100b-328b-4554-8846-1ab4389ec377.png)
，我自己用inkscape画了一个图标，开发者如果不嫌弃的话可以试一下这个图标 https://drive.google.com/file/d/1eFvCPYcuq9GUeaCQwxnUutCPAjWL6g0T/view?usp=sharing

**Comment by msojocs** [comment]
> 新版本图标已可以正常显示，但是会出现色彩断层 ![截图 2022-05-30 22-01-51](https://user-images.githubusercontent.com/33723146/171078635-a116100b-328b-4554-8846-1ab4389ec377.png) ，我自己用inkscape画了一个图标，开发者如果不嫌弃的话可以试一下这个图标 https://drive.google.com/file/d/1eFvCPYcuq9GUeaCQwxnUutCPAjWL6g0T/view?usp=sharing

可以的，感谢提供

**Comment by Peternal** [comment]
之前画的图标边距太小，这里重新修改了一下：
![io github msojocs bilibili](https://user-images.githubusercontent.com/33723146/171091265-e9c2437e-8cb5-4c3e-a09c-2047868c4dcd.svg)

**Comment by msojocs** [comment]
图标已替换，感谢 @Peternal 

似乎图标显示问题已解决，故关闭此issue。
