### ISSUE TITLE
漫游功能无法使用

### ISSUE THREAD

**Issue by wushuangliu070** [msojocs/bilibili-linux#40]
![image](https://user-images.githubusercontent.com/79258616/186387290-3cf5b64f-14cb-4781-b491-2d8bee1d9a53.png)

**Comment by wushuangliu070** [comment]
使用AppImage版本

**Comment by msojocs** [comment]
网络不好，文件没加载成功。
但是，我的retry按钮不见了。。。

**Comment by wushuangliu070** [comment]
> 网络不好，文件没加载成功。
> 但是，我的 <kbd>retry</kbd> 按钮不见了。。。

似乎不是网络的问题，direct和global proxy都试过了，其它的功能是正常的，之前的版本版本也可以正常加载

**Comment by bigshans** [comment]
设置页面同样是这个问题，之前设置过了现在还能用，就是设置页面坏了。

**Comment by msojocs** [comment]
修了
