### ISSUE TITLE
请问如何搜索非大陆地区番剧？

### ISSUE THREAD

**Issue by yburger** [msojocs/bilibili-linux#41]
ReadMe看到说支持外区搜索，但是直接搜索并没有搜到外区番剧，设置里的漫游页面也没有相应开关，是我看漏了什么吗？

**Comment by msojocs** [comment]
搜索页面 - 番剧

**Comment by yburger** [comment]
> 搜索页面 - 番剧

似乎搜索不到
[![v4m13V.png](https://s1.ax1x.com/2022/08/31/v4m13V.png)](https://imgse.com/i/v4m13V)
[![v4ml90.png](https://s1.ax1x.com/2022/08/31/v4ml90.png)](https://imgse.com/i/v4ml90)

**Comment by msojocs** [comment]
换个api服务器试试, 不行的话我再抽空检查一下。

**Comment by yburger** [comment]
换api服务器试了，依旧搜索不到

**Comment by yburger** [comment]
即时构建版本能搜索到泰区了，不过港澳台还是搜索不到

**Comment by msojocs** [comment]
> 即时构建版本能搜索到泰区了，不过港澳台还是搜索不到

目前港澳台的api被限制了，有解决方案；
但是，这需要api端做处理，我动不了。

还有一个方案，就是用手机版的接口，但这需要对数据结果进行处理，需要时间。
