### ISSUE TITLE
Ubuntu22.04最小化到系统托盘一段时间后无法再次打开

### ISSUE THREAD

**Issue by Mr-Spade** [msojocs/bilibili-linux#47]
- 系统：Ubuntu22.04
- 版本：1.7.2

非常感谢作者能提供客户端的Linux版本！我是用最新的稳定release的.deb包安装的，有一个小问题是在最小化到托盘之后，如果一段时间不打开，再想从托盘打开界面就会打不开。

用`ps -aux`看了下，进程似乎还在，但是不知道为什么界面出不来了。

另外，这个版本点击检查更新之后什么都没有出现，不知道这个算不算一个bug。

非常感谢！

**Comment by msojocs** [comment]
检查更新，就算查出来也没用。
过于久远，不知道还有没有问题，先关闭了。

**Comment by hhhhpaaa** [comment]
新版本也有这个问题 ubuntu24.04 1.17.3-2
