### ISSUE TITLE
xdg-icon-resource: No writable system icon directory found.

### ISSUE THREAD

**Issue by NekoYyang** [msojocs/bilibili-linux#49]
通过yay安装时报错

==> 正在验证 source 文件，使用sha256sums...
    bilibili-v1.8.2-1-x86_64.tar.gz ... 通过    bilibili ... 通过    bilibili.png ... 通过    bilibili.desktop ... 通过==> 正在删除现存的 $srcdir/ 目录...
==> 正在释放源码...
  -> 正在解压缩 bilibili-v1.8.2-1-x86_64.tar.gz，使用 bsdtar
==> 正在开始 prepare()...
==> 源代码已就绪。==> 正在创建软件包：bilibili-bin 1.8.2-1 (2022年12月31日 星期六 16时38分19秒)
==> 正在检查运行时依赖关系...
==> 正在检查编译时依赖关系==> 警告： 使用现存的 $srcdir/ 树==> 正在进入 fakeroot 环境...
==> 正在开始 package()...
xdg-icon-resource: No writable system icon directory found.
==> 错误： 在 package() 中发生一个错误。    正在放弃...
 -> 生成时出错: bilibili-bin

**Comment by NekoYyang** [comment]
系统为ArchLinux

**Comment by NekoYyang** [comment]
内核 6.1.1-zen1-1-zen

**Comment by msojocs** [comment]
相关包配置不再维护

**Comment by XiaY-Summer** [comment]
下载.tar.gz包解压，把文件放到你喜欢的位置，我放在/opt下了，然后创建个快捷方式，把快捷方式丢/usr/share/applications/里
以下是我的快捷方式配置，改一下图标和地址就可以用了
````
[Desktop Entry]
Encoding=UTF-8
Version=1.0
Type=Application
Terminal=false
Exec=/opt/bilibili/bin/bilibili
Name=哔哩哔哩Linux客户端
Icon=/opt/bilibili/bin/bilibili.jpeg
````
