### ISSUE TITLE
asar 缺失

### ISSUE THREAD

**Issue by DaBaiTuu** [msojocs/bilibili-linux#52]
采用拉取安装的方式，当然中途失败了，然后看了下报错，补全了两个 exiftool 和 7z 指令库 ，但是到了asar 是只能snap 安装,这个是真下不下来 ，求下解决方法，或者作者您那有本地安装asar的方法，抑或其他方法，谢谢

**Comment by msojocs** [comment]
`npm install asar -g`

**Comment by DaBaiTuu** [comment]
> `npm install asar -g`

我确实尝试过npm，但是安装npm的时候有如下问题：
‘’sudo apt install npm
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 npm : Depends: node-gyp (>= 0.10.9) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.‘’

**Comment by DaBaiTuu** [comment]
> `npm install asar -g`
谢谢，之前 安装 npm 的时候报了错，是库不协调，但是没尝试继续下去，我解决完npm安装问题，按你给的命令就ok了，谢谢
