### ISSUE TITLE
1.9.0的win版本安装后软件无法启动并且弹出错误窗口

### ISSUE THREAD

**Issue by bestWuTong** [msojocs/bilibili-linux#54]
1.9.0的win版本安装后软件无法启动并且弹出错误窗口
1.8.2版本可以正常使用
系统：Windows 10 22H2

![截图_20230119_103340](https://user-images.githubusercontent.com/72345506/213357364-ef4d7bb8-fb3d-42a7-96d8-bf842f0498c0.png)

后来我尝试将1.9.0的 bilibili\resources\app.asar 文件替换为1.8.2的，然后软件可以使用，只不过软件内版本显示为：v1.8.2，目前没有发现什么影响使用的问题

**Comment by msojocs** [comment]
Linux版本一样，`node_modules` 文件夹丢失。

**Comment by msojocs** [comment]
已处理
