### ISSUE TITLE
能否加入番剧出差页面修复与番剧繁翻简选项

### ISSUE THREAD

**Issue by CrazyDoge666** [msojocs/bilibili-linux#55]
希望可以修复番剧出差用户页面和番剧的CC字幕繁体自动翻译简体,繁体转简体脚本 https://greasyfork.org/zh-CN/scripts/431021-bilibili-b%E7%AB%99-%E7%95%AA%E5%89%A7cc%E5%AD%97%E5%B9%95%E8%87%AA%E5%8A%A8%E8%BD%AC%E6%8D%A2-%E7%BF%BB%E8%AF%91-%E7%B9%81%E4%BD%93%E8%BD%AC%E7%AE%80%E4%BD%93

**Comment by msojocs** [comment]
continuous已支持
https://github.com/msojocs/bilibili-linux/releases/tag/continuous

**Comment by msojocs** [comment]
v1.9.1-3
已支持
