### ISSUE TITLE
能否添加对windows on arm的支持

### ISSUE THREAD

**Issue by fkiliver** [msojocs/bilibili-linux#58]
Electron 6.0.8后支持windows on arm
官方文档https://www.electronjs.org/zh/docs/latest/tutorial/windows-arm

**Comment by msojocs** [comment]
加了，但是要你自己测试能不能用，我不会去测试的。

**Comment by msojocs** [comment]
不对，好像同名覆盖了。。。

**Comment by msojocs** [comment]
![image](https://user-images.githubusercontent.com/20937135/218236220-cfd4e2f7-e8ab-4424-9869-36d0e48e589e.png)
呃，一个安装包两个平台。。。

**Comment by fkiliver** [comment]
> ![image](https://user-images.githubusercontent.com/20937135/218236220-cfd4e2f7-e8ab-4424-9869-36d0e48e589e.png) 呃，一个安装包两个平台。。。

已测试，系统版本windows 22h2 arm64，处理器8cx gen 3，默认安装路径错误设置为programfile x86，但实际安装的是arm64版本。所有功能正常。
唯一问题是视频播放为软解，未调用gpu。

**Comment by o7451** [comment]
复现了，soc为高通850
