### ISSUE TITLE
在Windows on Arm上硬件解码不生效

### ISSUE THREAD

**Issue by fkiliver** [msojocs/bilibili-linux#59]
在arm64版本edge中播放视频可以正常调用硬件加速
但是edge arm64版中没有ffmpeg，暂不清楚edge是如何实现硬件加速的

**Comment by fkiliver** [comment]
这个项目能否发布为网页版本，类似YesPlayMusic？

**Comment by bigshans** [comment]
网页版的话，为啥不直接用B站网页呢？

**Comment by msojocs** [comment]
硬解不可能做到全平台兼容，网页版是不可能的，本末倒置。。。

**Comment by fkiliver** [comment]
> 网页版的话，为啥不直接用B站网页呢？

app对触屏更友好（

**Comment by fkiliver** [comment]
> 硬解不可能做到全平台兼容，网页版是不可能的，本末倒置。。。

不太了解electron开发，electron解码是用的ffmpeg吗？

**Comment by o7451** [comment]
同woa患者
