### ISSUE TITLE
[Bug] 托盘图标问题

### ISSUE THREAD

**Issue by funnychip796** [msojocs/bilibili-linux#6]
反映一个bug，狂按老板键后，托盘图标如下
![png](https://i.imgur.com/urh8tAp.png?1)

系统信息
OS: 20.04.1-Ubuntu
Kernel: 5.13.0-43-generic
DE: Gnome 3.36.8
WM: mutter

**Comment by msojocs** [comment]
这么强ヽ( ຶ▮ ຶ)ﾉ!!!

**Comment by msojocs** [comment]
已复现

**Comment by msojocs** [comment]
这个可能修不了了

https://github.com/electron/electron/issues/17622

**Comment by funnychip796** [comment]
辛苦了啊老哥
