### ISSUE TITLE
客户端硬件解码没有生效

### ISSUE THREAD

**Issue by DoveKi** [msojocs/bilibili-linux#60]
@msojocs 最新更新的硬解支持在你那边测试正常工作吗，能提供一下你那边相关硬件和系统环境吗
我这边相同的环境前和flags提下，在chrome里硬解正常，在客户端里硬解并没有工作

**chrome下测试**
环境
ubuntu 22.04
gnome xorg/x11
a卡+vaapi
我这边wayland/xwayland下原版chrome好像不管怎么设置都不能正常硬解，改用xorg登录硬解正常

我的chrome用的flags
/usr/bin/google-chrome-stable --ignore-gpu-blacklist --enable-gpu-rasterization --enable-zero-copy --disable-features=UseChromeOSDirectVideoDecoder --enable-features=VaapiVideoDecoder

进chrome://gpu里拉倒最底部
vaapi正确启用以后会显示所有支持的解码格式信息
![Screenshot from 2023-02-15 06-57-54](https://user-images.githubusercontent.com/8667391/218887691-b60f85f0-799e-492a-9bbd-3c7e252cae19.png)

播放测试任意4k60帧视频，比较容易观察cpu占用和是否掉帧
https://www.bilibili.com/video/BV1eQ4y127RB
4k最高画质，播放设置改为avc
验证检查chrome://media-internals/里当前播放视频页面的kIsPlatformVideoDecoder项是true，硬解正常
htop看cpu占用基本无负担 正常10%左右跳动

![Screenshot from 2023-02-15 06-24-24](https://user-images.githubusercontent.com/8667391/218879644-ebc0c1b9-5450-41b3-b743-82c60f200570.png)

**客户端播放器情况**
和上面chrome测试同一个视频和一样的播放设置
cpu占用明显没硬解，是软解的
在客户端里我不知道怎么进chrome://media-internals/和chrome://gpu检查相关信息
![Screenshot from 2023-02-15 06-45-24](https://user-images.githubusercontent.com/8667391/218881297-cc3ff534-c628-49e3-83e7-df256ccc292d.png)

我把所有app.commandLine.appendSwitch改成和我chrome的启动参数一样重新编译，一样没有任何效果

![Screenshot from 2023-02-15 07-36-32](https://user-images.githubusercontent.com/8667391/218887199-16e2110d-7e4f-457d-ada3-56c1d07349b1.png)

**Comment by msojocs** [comment]
不同平台参数应该不一致，我在Windows下跑的，我看能不能弄个自定义参数的支持。

**Comment by DoveKi** [comment]
> 

windows下跑啥意思，WSL？

**Comment by msojocs** [comment]
> 不同平台参数应该不一致，我在Windows下跑的，我看能不能弄个自定义参数的支持

不是wsl，就是windows的安装包那个。

**Comment by DoveKi** [comment]
> > 不同平台参数应该不一致，我在Windows下跑的，我看能不能弄个自定义参数的支持
> 
> 不是wsl，就是windows的安装包那个。
> 
> edit: Windows下我把参数全删了也有硬解。。。寄

windows下的chromium/electron默认缺省应该就有硬解 不需要再任何参数

**Comment by xiao-k233** [comment]
> > > 不同平台参数应该不一致，我在Windows下跑的，我看能不能弄个自定义参数的支持
> > 
> > 不是wsl，就是windows的安装包那个。
> > 
> > edit: Windows下我把参数全删了也有硬解。。。寄
> 
> windows下的chromium/electron默认缺省应该就有硬解 不需要再任何参数

对的

**Comment by everything411** [comment]
`electron chrome://gpu`可以看默认参数下的硬件解码支持，arch里electron17默认关闭硬解，electron22默认打开硬解，但是用electron22执行客户端，也同样无法使用硬件解码。chrome和firefox都能正常硬解b站avc。

**Comment by msojocs** [comment]
已添加自定义参数

**Comment by netphils** [comment]
> @msojocs 最新更新的硬解支持在你那边测试正常工作吗，能提供一下你那边相关硬件和系统环境吗 我这边相同的环境前和flags提下，在chrome里硬解正常，在客户端里硬解并没有工作
> 
> **chrome下测试** 环境 ubuntu 22.04 gnome xorg/x11 a卡+vaapi 我这边wayland/xwayland下原版chrome好像不管怎么设置都不能正常硬解，改用xorg登录硬解正常
> 
> 我的chrome用的flags /usr/bin/google-chrome-stable --ignore-gpu-blacklist --enable-gpu-rasterization --enable-zero-copy --disable-features=UseChromeOSDirectVideoDecoder --enable-features=VaapiVideoDecoder
> 
> 进chrome://gpu里拉倒最底部 vaapi正确启用以后会显示所有支持的解码格式信息 ![Screenshot from 2023-02-15 06-57-54](https://user-images.githubusercontent.com/8667391/218887691-b60f85f0-799e-492a-9bbd-3c7e252cae19.png)
> 
> 播放测试任意4k60帧视频，比较容易观察cpu占用和是否掉帧 https://www.bilibili.com/video/BV1eQ4y127RB 4k最高画质，播放设置改为avc 验证检查chrome://media-internals/里当前播放视频页面的kIsPlatformVideoDecoder项是true，硬解正常 htop看cpu占用基本无负担 正常10%左右跳动
> 
> ![Screenshot from 2023-02-15 06-24-24](https://user-images.githubusercontent.com/8667391/218879644-ebc0c1b9-5450-41b3-b743-82c60f200570.png)
> 
> **客户端播放器情况** 和上面chrome测试同一个视频和一样的播放设置 cpu占用明显没硬解，是软解的 在客户端里我不知道怎么进chrome://media-internals/和chrome://gpu检查相关信息 ![Screenshot from 2023-02-15 06-45-24](https://user-images.githubusercontent.com/8667391/218881297-cc3ff534-c628-49e3-83e7-df256ccc292d.png)
> 
> 我把所有app.commandLine.appendSwitch改成和我chrome的启动参数一样重新编译，一样没有任何效果
> 
> ![Screenshot from 2023-02-15 07-36-32](https://user-images.githubusercontent.com/8667391/218887199-16e2110d-7e4f-457d-ada3-56c1d07349b1.png)

wayland版本chromium需要改成`--enable-features=VaapiVideoDecodeLinuxGL`
我用`chromium --ignore-gpu-blacklist --enable-features=VaapiVideoDecodeLinuxGL`可以在chrome://gpu正常显示解码信息。

**Comment by DoveKi** [comment]
> > 我这边wayland/xwayland下原版chrome好像不管怎么设置都不能正常硬解，改用xorg登录硬解正常
> 
> 改成`--enable-features=VaapiVideoDecodeLinuxGL`试试? 我用`chromium --ignore-gpu-blacklist --enable-features=VaapiVideoDecodeLinuxGL`可以在chrome://gpu正常显示解码信息，但是这个软件里还是不行。

VaapiVideoDecodeLinuxGL这个参数是最近chromium的版本刚有的
我现在没折腾了你可以试试加进app.commandLine.appendSwitch里面编译试试
