### ISSUE TITLE
点赞不正常

### ISSUE THREAD

**Issue by LTreeshu** [msojocs/bilibili-linux#65]
在个人动态页上所有点赞失败，播放页点赞有时会失败

**Comment by msojocs** [comment]
这个不清楚，我没动太多源码，弄不了。

**Comment by LTreeshu** [comment]
新的版本已经没有这个问题了，感谢大佬回复❤️❤️❤️发自我的手机-------- 原始邮件 --------发件人： msojocs ***@***.***>日期： 2023年6月3日周六 12:29收件人： msojocs/bilibili-linux ***@***.***>抄送： LTreeshu ***@***.***>, Author ***@***.***>主    题： Re: [msojocs/bilibili-linux] 点赞不正常 (Issue #65)
这个不清楚，我没动太多源码，弄不了。
