### ISSUE TITLE
全屏播放时暂停后再次播放会产生卡顿

### ISSUE THREAD

**Issue by WhateverMO** [msojocs/bilibili-linux#67]
这是我的系统配置
![image](https://user-images.githubusercontent.com/75033001/229065562-a46e9059-afb1-4722-b2cd-8931ab3593d1.png)
当在bilibili设置中关闭GPU加速不会产生此问题，当开启GPU加速时，必复现此问题！

**Comment by TinyHai** [comment]
这应该是n卡的问题

**Comment by WhateverMO** [comment]
经5月20日测试，此问题已消失
