### ISSUE TITLE
该更新啦~

### ISSUE THREAD

**Issue by aoligei-max** [msojocs/bilibili-linux#7]
用AUR助手paru下载bilibili-bin后提示校验值错误,经检查后发现bilibili客户端的“bili_win-install.exe“的校验值错误,跳过校验值检测后依然无正常启动

wiliam@R9000P ~/.cache/paru/clone/bilibili-bin (git)-[master] % bilibili       
15:42:02.853 (AppBootstrap) › Start error, code: 001
警告
程序异常，无法正常运行！错误代码：001

再次检查后发现 "bili_win-install.exe“ 已经更新到1.1.2了(而非1.1.1-4)

**Comment by msojocs** [comment]
get

**Comment by aoligei-max** [comment]
> get 它这个链接不带版本号就离谱

叔叔太坏了,链接竟然不带版本号(哭
