### ISSUE TITLE
archlinux下检测不到flags配置文件

### ISSUE THREAD

**Issue by kznr02** [msojocs/bilibili-linux#70]
我设置了$HOME/.config/bilibili-flags.conf文件以开启wayland和中文输入法修复（通过开启GTK4支持），但软件无法检测到，不知道是我的设置出现了错误还是如何，如果通过命令行传入，wayland可以正常开启，但GTK4无法开启，报错如下。

> (process:13730): Gtk-ERROR **: 20:12:05.973: GTK 2/3 symbols detected. Using GTK 2/3 and GTK 4 in the same process is not supported

flags如下：
--enable-feature=UseOzonePlatform --ozone-platform=wayland --gtk-version=4

**Comment by msojocs** [comment]
你哪里看的这个配置操作，我并没有主动支持过这个文件。

**Comment by kznr02** [comment]
> 你哪里看的这个配置操作，我并没有主动支持过这个文件。

似乎是archlinux package特有的一种机制，不知能否提供支持，类似于chromium和vscode的chromium-flags.conf和code-flags.conf

**Comment by kznr02** [comment]
> 抱歉，不能支持

看了一下似乎得和打包者联系，我先关闭issue了
