### ISSUE TITLE
无法切换深色和浅色模式，并且有按钮位置似乎不正确

### ISSUE THREAD

**Issue by xiaozhangup** [msojocs/bilibili-linux#72]
单击这里没法直接换颜色，需要客户端重启才能显现
![图片](https://github.com/msojocs/bilibili-linux/assets/68374769/50107f28-fcec-4b68-880a-d87e6df84c78)

在设置中，设置和漫游贴到一起去了
![图片](https://github.com/msojocs/bilibili-linux/assets/68374769/828883b7-1dae-405e-bff0-79333eb2061f)

**Comment by msojocs** [comment]
深色模式切换，已复现，`1.10.1-1` -> `1.10.1-2` 出现的；

漫游按钮一直都这样（

**Comment by xiaozhangup** [comment]
> 深色模式切换，已复现，`1.10.1-1` -> `1.10.1-2` 出现的；
> 
> 漫游按钮一直都这样（

但这样感觉有点小丑，至少来点空格（（（（

**Comment by msojocs** [comment]
已处理
