### ISSUE TITLE
sha256sums 检查未通过，版本bilibili-bin 1.10.1-4 

### ISSUE THREAD

**Issue by kemikoza** [msojocs/bilibili-linux#73]
![image](https://github.com/msojocs/bilibili-linux/assets/114063789/d15f6965-0486-4ce7-af6e-47f1a547dcc1)
应该将第二个sha256sums空格删除
PKGBUILD，第21行
`'e7fd848643d05bdbaab39df1fd975fed593055328862630f284ad0630a5d793d '`
应将其改为
`'e7fd848643d05bdbaab39df1fd975fed593055328862630f284ad0630a5d793d'`

**Comment by msojocs** [comment]
aur包不是我维护的
