### ISSUE TITLE
bilibili.Setup.1.11.4.exe 安装后没有漫游

### ISSUE THREAD

**Issue by Tianzhen1016** [msojocs/bilibili-linux#79]
==还需要下哪个覆盖吗还是

**Comment by Tianzhen1016** [comment]
准确来说 有时候有有时候没有

**Comment by msojocs** [comment]
看不见漫游设置页面？

**Comment by msojocs** [comment]
我重开了10次，都可以看见漫游设置入口。

**Comment by Tianzhen1016** [comment]
> 我重开了10次，都可以看到漫游设置入口。

![11111](https://github.com/msojocs/bilibili-linux/assets/32900421/4ac70dbb-1ade-4a15-8e52-6dda70e8fbd0)
有时候会出现这样
