### ISSUE TITLE
视频播放时无声音

### ISSUE THREAD

**Issue by Sagecheni** [msojocs/bilibili-linux#81]
无论是appimage还是yay拉取安装的程序都没办法播出声音，但视频能正常播放

**Comment by msojocs** [comment]
你的浏览器看视频有声音吗

**Comment by Sagecheni** [comment]
浏览器和其他播放器都是有声音的

**Comment by msojocs** [comment]
什么系统啊

**Comment by Sagecheni** [comment]
arch

**Comment by msojocs** [comment]
感觉唯一的可能是音频文件没加载出来。
不好处理

**Comment by msojocs** [comment]
试试看把`area_unlimit`文件夹删了看看

**Comment by Sagecheni** [comment]
我的mediaplayer是能检测到bilibili的，但是就是没声音
![image](https://github.com/msojocs/bilibili-linux/assets/113398362/528f0047-733a-404b-bb40-64313b58e3f3)

**Comment by Sagecheni** [comment]
但是好像Audio 检测不到

**Comment by msojocs** [comment]
你先把`area_unlimit`文件夹删了，这个插件会拦截网络请求。
不行的话，我明天加个开发者工具的开关，看看网络请求。

**Comment by msojocs** [comment]
已添加开发者工具支持

https://github.com/msojocs/bilibili-linux#%E5%BC%80%E5%8F%91%E8%80%85%E5%B7%A5%E5%85%B7
