### ISSUE TITLE
直播间发弹幕显示没登陆

### ISSUE THREAD

**Issue by Cyberczy** [msojocs/bilibili-linux#85]
直播间右边的弹幕区也刷不出来下方的礼物区也是

**Comment by msojocs** [comment]
暂时没有复现

**Comment by Cyberczy** [comment]
aur新版本已修复

**Comment by msojocs** [comment]
版本都不一样还来这儿问
![JSYTP{ X$W SQL5MPZQMCKQ](https://github.com/msojocs/bilibili-linux/assets/20937135/267ff97f-2c0e-4187-9ee0-2af741349657)
