### ISSUE TITLE
up主主页上面一条白色横栏，无法查看投稿

### ISSUE THREAD

**Issue by FadeJay** [msojocs/bilibili-linux#90]
使用最新的1.21.1-2版本，点进up主主页，会在最上面有一大条白色的横栏，动态页可以查看，但投稿显示空白
![111](https://github.com/msojocs/bilibili-linux/assets/15902208/6bc0bb4f-c562-4006-a0b7-467217416c35)

**Comment by msojocs** [comment]
已复现

**Comment by shenmo7192** [comment]
在这插眼，deepin商店上架版本问题复现

**Comment by msojocs** [comment]
已处理

**Comment by FadeJay** [comment]
> 已处理

点进其他up主的空间恢复正常，但自己本人的空间主页存在同样的问题

**Comment by msojocs** [comment]
我打开自己的是正常的

**Comment by FadeJay** [comment]
> 我打开自己的是正常的

我卸载重装后正常了，可能是之前的缓存有问题

**Comment by msojocs** [comment]
ok
