### ISSUE TITLE
升级到1.12.3后 Windows 上启动失败

### ISSUE THREAD

**Issue by Howard20181** [msojocs/bilibili-linux#94]
什么界面都没有
如果什么 flag 都不加启动几秒后会出现一条日志
`Passthrough is not supported, GL is disabled, ANGLE is` is什么后面是没有的，除了这条日志没有其他错误
进程不退出

如果加上 `disable-gpu`
什么报错都没有
也一样没有界面
进程不退出

如果再加上 `no-sandbox`
会 `ERROR:gpu_process_host.cc(979)] GPU process exited unexpectedly: exit_code=-2147483645` 
崩溃9次之后进程退出
```
WARNING:gpu_process_host.cc(1284)] The GPU process has crashed 9 time(s)
FATAL:gpu_data_manager_impl_private.cc(448)] GPU process isn't usable. Goodbye.
```
一样什么界面都没有，进程退出
之后无论加不加 `no-sandbox` 都会这样崩溃

所有测试都加了 `enable-logging=file`
但是日志文件是空的

测试安装官方未修改的原版 1.12.3 正常使用

**Comment by msojocs** [comment]
已处理
