### ISSUE TITLE
HD登录点击之后没有反应

### ISSUE THREAD

**Issue by liuran001** [msojocs/bilibili-linux#95]
- 客户端版本: v1.12.5-1 (https://github.com/msojocs/bilibili-linux/releases/download/v1.12.5-1/bilibili.Setup.1.12.5.exe)
- 系统版本: Windows 11 Pro

RT，漫游设置中的 HD登录 点击后没有任何反应，控制台无输出，无法正常解析外区番剧

![image](https://github.com/msojocs/bilibili-linux/assets/32791471/9333bdac-d0f0-4d60-bd86-1c62ce7db04c)
![image](https://github.com/msojocs/bilibili-linux/assets/32791471/b882af4f-7dc6-46a8-9acf-59fdc307bf84)

**Comment by cxw620** [comment]
解析服务器问题吧, 把大陆填上, 或者换别的.

**Comment by msojocs** [comment]
你确定点了？

点了会有这种日志出现：

![image](https://github.com/msojocs/bilibili-linux/assets/20937135/01cd98e7-8e11-4aa5-bf1e-1b96c2b3e266)

**Comment by liuran001** [comment]
> 你确定点了？
> 
> 点了会有这种日志出现：
> 
> edit: appkey=xxxx
> 
> ![image](https://user-images.githubusercontent.com/20937135/280502341-01cd98e7-8e11-4aa5-bf1e-1b96c2b3e266.png)

@msojocs 电脑也换了，服务器也换过了，一样的问题

你看我上面保存点了 `saveServer` 是有日志的，那个 HD登录 就怎么点都没反应
![image](https://piccdn.obdo.cc/file/03e574112cb917f932728.jpg)

**Comment by msojocs** [comment]
点击按钮后有没有什么报错；

看看点击按钮后有没有新增网络请求。

**Comment by msojocs** [comment]
https://github.com/msojocs/bilibili-linux/releases/tag/continuous

直接试一下刚构建的版本。

**Comment by liuran001** [comment]
> 设置我没动

那应该是b站或者弱智windows的问题，群友测试确实是好的（

**Comment by liuran001** [comment]
> 点击按钮后有没有什么报错；
> 
> 看看点击按钮后有没有新增网络请求。

感觉点击事件完全没绑定上按钮，无报错无请求



> https://github.com/msojocs/bilibili-linux/releases/tag/continuous
> 
> 直接试一下刚构建的版本。

从状态栏图标右键进去设置没问题了，但是现在侧边栏设置图标坏了，点了无反应无报错无网络请求

这下是 HD 登录 的问题转到设置上了（

@msojocs

**Comment by msojocs** [comment]
设置我没动
