### ISSUE TITLE
[BUG] 泰区视频无法播放

### ISSUE THREAD

**Issue by msojocs** [msojocs/bilibili-linux#97]
![image](https://github.com/msojocs/bilibili-linux/assets/20937135/db3f8449-1621-4fe2-a2f5-f927a4f35cbc)

HD 的 `access_key` 似乎没有权限？

**Comment by cxw620** [comment]
东南亚区域理论上需要在请求参数指定`area=th`，access_key 仅用于服务器鉴权，主站和东南亚已经是分开的，720p以上得服主配置自己的登录信息。发自我的手机-------- 原始邮件 --------发件人： msojocs ***@***.***>日期： 2023年11月27日周一 上午10:40收件人： msojocs/bilibili-linux ***@***.***>抄送： Subscribed ***@***.***>主    题： [msojocs/bilibili-linux] [BUG] 泰区视频无法播放 (Issue #97)
image.png (view on web)
HD 的 access_key 似乎没有权限？

**Comment by msojocs** [comment]
> 东南亚区域理论上需要在请求参数指定`area=th`，access_key 仅用于服务器鉴权，主站和东南亚已经是分开的，720p以上得服主配置自己的登录信息。发自我的手机-------- 原始邮件 --------发件人： msojocs ***@***.***>日期： 2023年11月27日周一 上午10:40收件人： msojocs/bilibili-linux ***@***.***>抄送： Subscribed ***@***.***>主 题： [msojocs/bilibili-linux] [BUG] 泰区视频无法播放 (Issue #97) image.png (view on web) HD 的 access_key 似乎没有权限？ —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

确实，我刚刚又试了一下，可以的。
运气不好，刚好用的时候服务器的鉴权出了点问题。
