### ISSUE TITLE
建议添加一个刷新的快捷键

### ISSUE THREAD

**Issue by ashin520** [msojocs/bilibili-linux#98]
本人是键盘党，平常喜欢用快捷键提高效率。
查看了该bilibili linux客户端的所有快捷键，貌似没有刷新的快捷键。
用F5是可以刷新，但是f5的刷新是整个桌面刷新，会有1S左右的延迟，体验不是很好，而右下角的刷新按钮又需要用鼠标去点击，有点繁琐。
希望能采纳我的建议，谢谢开发者，您的这个linux客户端体验非常不错！！！
感谢您的付出！

**Comment by ashin520** [comment]
> 整个桌面刷新是什么意思？

https://github.com/msojocs/bilibili-linux/assets/92786169/97591011-010c-419f-ac97-2f9ec14946d1

我录了个屏幕给您看，按F5是整个窗口刷新。能不能做个右下角刷新的快捷键呢

**Comment by msojocs** [comment]
你是不是打开了控制台，然后按F5

**Comment by msojocs** [comment]
无响应，关闭
